'use strict';

(function () {

  var PIN_WIDTH = 50;
  var PIN_HEIGHT = 70;
  var MIN_WINDOW_HEIGHT = 130;
  var MAX_WINDOW_HEIGHT = 630;

  var MAIN_PIN_WIDTH = 64;
  var MAIN_PIN_HEIGHT = 82;
  var WINDOW_WIDTH = 1200;
  var ESC_KEY_CODE = 27;

  window.data = {
    PIN_WIDTH: PIN_WIDTH,
    PIN_HEIGHT: PIN_HEIGHT,
    MIN_WINDOW_HEIGHT: MIN_WINDOW_HEIGHT,
    MAX_WINDOW_HEIGHT: MAX_WINDOW_HEIGHT,
    WINDOW_WIDTH: WINDOW_WIDTH,
    MAIN_PIN_WIDTH: MAIN_PIN_WIDTH,
    MAIN_PIN_HEIGHT: MAIN_PIN_HEIGHT,
    ESC_KEY_CODE: ESC_KEY_CODE
  };

})();
